### PR TITLE
Fixes #907

### LINKED ISSUE #907: Signal regression from 0.9 -> 0.10: only first item emitted on `repeat` source.
The following chunk of code only results in a single item emitted on 0.10.0-M4 (also tested on M2).

```
import fs2._
import cats.effect.IO
import scala.concurrent.ExecutionContext.Implicits.global
import scala.concurrent.duration._

def log[A](prefix : String) : Pipe[IO,A,A] = { in =>
  in.evalMap(i => IO { println(prefix + ">>" + i.toString) ; i} )
}

case class Price(key : Char, price : Double)
object Price {
  def random : IO[Price] = IO {
    val key = 'A' + (scala.math.random() * 10.0).toInt toChar
    val price = scala.math.random()
    Price(key, price)
  }
}

val in : Stream[IO,Price] = (Stream eval Price.random repeat) through log("in")

val sig : Stream[IO, async.immutable.Signal[IO,Option[Price]]] =
  async.immutable.Signal.holdOption(in)

val out : Stream[IO,Option[Price]] =
  sig flatMap (_.discrete) take 20 through log("out")

out.runLog.unsafeRunTimed(1 second)
```

I would expect this to emit the 20 items. It only outputs:
```
in>>Price(H,0.30250069403636715)
out>>None
out>>Some(Price(H,0.30250069403636715))
```

On 0.9.7, with the following code:

```
import fs2._

implicit def strat = Strategy.fromCachedDaemonPool()
def log[A](prefix : String) : Pipe[Task,A,A] =
  _.evalMap(i => Task.delay{ println(prefix + ">>" + i.toString) ; i } )

case class Price(key : Char, price : Double)
object Price {
  def random : Task[Price] = Task {
    val key = 'A' + (scala.math.random() * 10.0).toInt toChar
    val price = scala.math.random()
    Price(key, price)
  }
}

val in : Stream[Task,Price] = (Stream eval Price.random repeat) through log("in")

val sig : Stream[Task, async.immutable.Signal[Task,Option[Price]]] =
  async.immutable.Signal.holdOption(in)

val out : Stream[Task,Option[Price]] =
  sig flatMap (_.discrete) take 20 through log("out")

out.runLog.unsafeRun()
```
This prints out multiple `in`s and the 20 `out`s (can't see the output - it's cut off, sample below):

```
in>>Price(A,0.32971324020042525)
in>>Price(D,0.29919574847430286)
in>>Price(H,0.9111423166252853)
in>>Price(J,0.5500450896250947)
in>>Price(F,0.22712762271018438)
in>>Price(H,0.44739601322878864)
in>>Price(B,0.7649178222004639)
in>>Price(I,0.08453299145449888)
in>>Price(B,0.9298880933223229)
in>>Price(C,0.8484940029373574)
in>>Price(I,0.9747919045403481)
in>>Price(H,0.14794885880903685)
in>>Price(H,0.27389323535519183)
in>>Price(C,0.23817026370678984)
in>>Price(D,0.2903977744468541)
in>>Price(A,0.6209111201757896)
in>>Price(J,0.7897043931941421)
in>>Price(A,0.7167284670123723)
in>>Price(D,0.3363488372388195)
in>>Price(H,0.5082710285336824)
in>>Price(G,0.8791137829005642)
in>>Price(D,0.63527340408363)
out>>Some(Price(H,0.5082710285336824))
in>>Price(G,0.27663035256663004)
in>>Price(I,0.9854773973480855)
in>>Price(F,0.9448985707882575)
in>>Price(A,0.17042652049262041)
out>>Some(Price(F,0.9448985707882575))
in>>Price(C,0.4185048818658893)
out>>Some(Price(A,0.17042652049262041))
out>>Some(Price(C,0.4185048818658893))
in>>Price(I,0.4010571085499287)
out>>Some(Price(I,0.4010571085499287))
in>>Price(E,0.5089171525630363)
in>>Price(J,0.18523549641820947)
Output exceeds cutoff limit.
```

@SystemFw  reproduced this too.

### PR DESCRIPTION
**Pull request by mpilquist**
Introduced `s.concurrently(t)` as a safe replacement for `s.mergeHaltR(t.drain)`. Removed `mergeHaltL` and `mergeHaltR`. Changed `hold` to be implemented with `concurrently`.

@pchlupacek This should cover everything from #911. /cc @SystemFw

### CODE REVIEW

File: core/shared/src/main/scala/fs2/Stream.scala [hunk 1]
```diff
@@ -1722,6 +1764,16 @@ object Stream {
...
      *
+     * Note: `this` and `that` are each pulled for a segment. Upon receiving
+     * a segment, it is emitted downstream. Depending on how that element is
+     * processed, the remainder of `this` and `that` may never be consulted
+     * again (e.g., `a.merge(b) >> Stream.constant(0)`). A common case where
+     * this can be problematic is draining a stream that publishes to a
+     * concurrent data structure and merging it with a consumer from the same
+     * data structure. In such cases, use `consumer.concurrently(producer)`
+     * instead of `consumer.mergeHaltR(producer.drain)` to ensure the producer
+     * continues to run in paralle with consumer processing.
```
Comment (pchlupacek) [inline core/shared/src/main/scala/fs2/Stream.scala]: *parallel

File: core/shared/src/main/scala/fs2/async/async.scala [hunk 2]
```diff
@@ -57,12 +57,14 @@ package object async {
    *
    * @param source   discrete stream publishing values to this signal
    */
-  def hold[F[_]:Effect,A](initial: A, source: Stream[F, A])(implicit ec: ExecutionContext): Stream[F, immutable.Signal[F,A]] =
-     immutable.Signal.hold(initial, source)
+  def hold[F[_],A](initial: A, source:Stream[F,A])(implicit F: Effect[F], ec: ExecutionContext): Stream[F,immutable.Signal[F,A]] =
+    Stream.eval(signalOf[F,A](initial)) flatMap { sig =>
+      Stream(sig).concurrently(source.flatMap(a => Stream.eval_(sig.set(a))))
```
Comment (pchlupacek) [inline core/shared/src/main/scala/fs2/async/async.scala]: source evalMap (... ) ?

File: docs/guide.md [hunk 3]
```diff
@@ -478,9 +478,9 @@ scala> Stream(1,2,3).merge(Stream.eval(IO { Thread.sleep(200); 4 })).runLog.unsa
 res38: Vector[Int] = Vector(1, 2, 3, 4)
 ```
 
-The `merge` function is defined in [`pipe2`](../core/shared/src/main/scala/fs2/pipe2.scala), along with other useful concurrency functions, like `interrupt` (halts if the left branch produces `false`), `either` (like `merge` but returns an `Either`), `mergeHaltBoth` (halts if either branch halts), and others.
+The `merge` function supports concurrency. FS2 has a number of other useful concurrency functions like `concurrently` (runs another stream concurrently and discards its output), `interrupt` (halts if the left branch produces `false`), `either` (like `merge` but returns an `Either`), `mergeHaltBoth` (halts if either branch halts), and others.
```
Comment (pchlupacek) [inline docs/guide.md]: Michael, I am just wondering, the interrupt now, wouldn't it suffer from the same issues like mergeDrainX? I mean currently, interrupt wouldn't be able to interrupt the other branch of merge, unless something processes the elements correct? Not sure if that couldn't be problematic too ?

Comment (mpilquist) [inline docs/guide.md]: Interrupt relies on merging both streams and inspecting the emitted interruption value in the merged output. As such, it's definitely not safe to use with a downstream that emits an infinite stream. I think this is OK though -- this has always been its behavior.

File: core/shared/src/main/scala/fs2/Stream.scala [hunk 4]
```diff
@@ -1417,6 +1417,48 @@ object Stream {
...
+     * The resulting stream terminates upon termination of this stream. The background stream will
+     * be interrupted at that point. Early termination of `that` does not terminate the resulting stream.
+     *
+     * Any errors that occur in either `this` or `that` stream result in the overall stream terminating
+     * with an error.
+     *
+     * Upon finalization, the resulting stream will interrupt the background stream and wait for it to be
+     * finalized.
+     *
+     * This method is similar to `this mergeHaltL that.drain` but ensures the `that.drain` stream continues
```
Comment (SystemFw) [inline core/shared/src/main/scala/fs2/Stream.scala]: I like this explanation, but it refers to `mergeHaltL`, which is removed. Likely to be confusing to someone who's not familiar with the old API perhaps?

Comment (mpilquist) [inline core/shared/src/main/scala/fs2/Stream.scala]: I left `mergeHalt{L,R,Both}` -- only removed `mergeDrain{L,R}`

Comment (SystemFw) [inline core/shared/src/main/scala/fs2/Stream.scala]: Right, so there's a typo in the docs below I think

File: docs/migration-guide-0.10.md [hunk 5]
```diff
@@ -126,6 +126,22 @@ Scheduler[IO](corePoolSize = 1).flatMap { scheduler =>
...
+  Stream.emit(s) mergeHaltR source.evalMap(s.set).drain
+}
+```
+
+The general idea behind this pattern is to create a producer and a consumer and then combine them in to a single stream by merging the consumer with the result of draining the producer. In 0.10, the two streams used in a merge are only consulted when downstream needs an element. As a result, it's possible to deadlock when using this pattern. This pattern relies on the fact that the drained producer will continue to execute in parallel with the consumer, *even when the downstream never asks for another element from the merged stream*.
+
+To address this use case, the `concurrently` method has been added. Instead of `consumer.mergeHaltR(producer.drain)`, use `consumer.concurrently(producer)`. See the ScalaDoc for `concurrently` for more details.
+
+Given that most usage of merging a drained stream with another stream should be replaced with `concurrently`, we've removed `mergeHaltL` and `mergeHaltR`.
+
```
Comment (SystemFw) [inline docs/migration-guide-0.10.md]: Do you mean `mergeDrainL` and `mergeDrainR` here?

Comment (mpilquist) [inline docs/migration-guide-0.10.md]: Yep :)

File: core/jvm/src/test/scala/fs2/ConcurrentlySpec.scala [hunk 6]
```diff
@@ -0,0 +1,37 @@
...
+    }
+
+    "when primary stream termiantes, background stream is terminated" in forAll { (s: PureStream[Int]) =>
+      var bgDone = false
+      val bg = Stream.repeatEval(IO(1)).onFinalize(IO(bgDone = true))
+      val prg = Scheduler[IO](1).flatMap(scheduler => (scheduler.sleep_[IO](25.millis) ++ s.get).concurrently(bg))
+      runLog(prg)
+      bgDone shouldBe true
+    }
+  }
```
Comment (pchlupacek) [inline core/jvm/src/test/scala/fs2/ConcurrentlySpec.scala]: @mpilquist can you please verify that program below terminates before 1 minute timeout ? Note the main program emits once then uses the discrete of signal in flatMap
```
Stream.eval(async.signalOf[IO, Int](-1)) flatMap { signal => 
  (Stream.emit(signal)).concurrently( 
     (Stream.range(0, 10) ++ Stream.fail(new Throwable("BOOM")) .evalMap(signal.set)
  )
} flatMap { signal => 
 signal.discrete  
}}

 

```

File: docs/guide.md (hunk 3 above)
Comment (pchlupacek) [inline docs/guide.md]: I think in 0.9 this would have completely different behaviour than in 0.10

```scala

val s1: Stream[Int] = ???

val s2: Stream[Boolean]  = time.sleep_(100 millis) ++ Stream.emit(true)

(s1 interruptWhen s2) flatMap { i =>
 Stream.emit(i) ++ sleep_(1.minute)
}
```
In 0.9 this will interrupt s1 in 100 millis, however in 0.10 this will interrupt s1 in 1.minute

Comment (mpilquist) [inline docs/guide.md]: @pchlupacek Just tested this under 0.9.7 and confirmed that it interrupts after 1 minute, not after 100 milliseconds.

File: core/jvm/src/test/scala/fs2/ConcurrentlySpec.scala (hunk 6 above)
Comment (mpilquist) [inline core/jvm/src/test/scala/fs2/ConcurrentlySpec.scala]: @pchlupacek That program hangs. The background stream fails, which causes the primary stream to have its interruption signal set. But the primary stream never inspects the interruption signal b/c it is still focused on infinite stream returned from discrete. It's not clear to me why this pattern works in 0.9 given the way interrupt is implemented.

Comment (mpilquist) [inline core/jvm/src/test/scala/fs2/ConcurrentlySpec.scala]: @pchlupacek Ah ha! It hangs in 0.9 as well for the same reason. E.g.

```scala
Stream.eval(async.signalOf[Task,Boolean](false)).flatMap(s => Stream.eval_(Task.start(s.set(true).schedule(1.second))) ++ Stream.emit(s).interruptWhen(s)).flatMap(s => s.discrete).runLog.unsafeRunAsync(println)
```

Comment (pchlupacek) [inline core/jvm/src/test/scala/fs2/ConcurrentlySpec.scala]: @mpilquist in 0.9 it won't work. in 0.8 however, that will work. My concern here is that if we won't be able to somehow resolve this, then this `concurrently` pattern is inherently unsafe and will lead to unsound dead-locked programs. Also, current mergeDrainL, R, etc patterns are suffering from this, and as such migration of complex concurrents programs from 0.8 to 0.9 is really painful :-(. 

@djspiewak, @pchiusano  I would be really grateful on your input here, I think it is really important design decision we are going to make here, and hence your worked on many concurrent primitives, perhaps you may share your opinion on this ?

Comment (pchlupacek) [inline core/jvm/src/test/scala/fs2/ConcurrentlySpec.scala]: @mpilquist yeh, you were faster than me :-)

Comment (mpilquist) [inline core/jvm/src/test/scala/fs2/ConcurrentlySpec.scala]: @pchlupacek Note that it's not `concurrently` that's inherently unsafe but rather the fact that `interrupt` is implemented in terms of `merge`. If we could implement `interrupt` in terms of `concurrently` instead, it would work fine. I don't know how to do that though -- we'd need some way to communicate the interruption to the main interpreter loop.

Comment (mpilquist) [inline core/jvm/src/test/scala/fs2/ConcurrentlySpec.scala]: Well that's kind of strange I guess - `concurrently` is implemented with `interruptWhen` and `interruptWhen` would be implemented in terms of `concurrently`. So ignore that comment.

Comment (pchlupacek) [inline core/jvm/src/test/scala/fs2/ConcurrentlySpec.scala]: @mpilquist exactly. Is all about the laws here :-) essentially currently we are breaking the law that when right side (Stream[F, Unit]) fails, that resulting stream fails too :-)

Comment (pchlupacek) [inline core/jvm/src/test/scala/fs2/ConcurrentlySpec.scala]: And that said, this is for any pipe2, which I am quite sure will suffer from this behaviour.

Comment (pchlupacek) [inline core/jvm/src/test/scala/fs2/ConcurrentlySpec.scala]: :-) Catch-22

**Comment by mpilquist** [comment]
Tell me more, I'm not seeing it...

**Comment by pchlupacek** [comment]
I was merely just commenting on your idea with concurrently/interruptWhen which I considered `Catch-22` like

**Comment by mpilquist** [comment]
After more discussion with @pchlupacek offline, we decided to merge this and open a new issue for the concerns around `interruptWhen`.
