### PR TITLE
Fixed #1709 - .to(Collector) syntax fix for 2.12

### LINKED ISSUE #1709: The new collector syntax doesn't work with Scala 2.12 when the result type is explicitly specified
I'm not sure whether this should be treated as an fs2 issue or a Scala issue... Probably, both.

```scala
scala> Stream.empty[Id].covaryOutput[Byte].compile.to(Chunk)
res1: fs2.Chunk[Byte] = empty

scala> Stream.empty[Id].covaryOutput[Byte].compile.to(Chunk): Chunk[Byte]
<console>:21: error: type mismatch;
 found   : fs2.Chunk.type
 required: fs2.internal.Factory[Byte,fs2.Chunk[Byte]]
    (which expands to)  scala.collection.generic.CanBuildFrom[Nothing,Byte,fs2.Chunk[Byte]]
       Stream.empty[Id].covaryOutput[Byte].compile.to(Chunk): Chunk[Byte]
                                                      ^

scala> val c: Collector.Aux[Byte, Chunk[Byte]] = Chunk
c: fs2.Collector.Aux[Byte,fs2.Chunk[Byte]] = fs2.CollectorK$$anon$6@2860828f

scala> Stream.empty[Id].covaryOutput[Byte].compile.to(c): c.Out
<console>:22: error: type mismatch;
 found   : fs2.Collector.Aux[Byte,fs2.Chunk[Byte]]
    (which expands to)  fs2.Collector[Byte]{type Out = fs2.Chunk[Byte]}
 required: fs2.internal.Factory[Byte,fs2.Chunk[Byte]]
    (which expands to)  scala.collection.generic.CanBuildFrom[Nothing,Byte,fs2.Chunk[Byte]]
       Stream.empty[Id].covaryOutput[Byte].compile.to(c): c.Out
                                                      ^
```

I've managed to find this magic workaround:

```scala
scala> val s = Stream.empty[Id].covaryOutput[Byte].compile.to(Chunk)
s: fs2.Chunk[Byte] = empty

scala> s: Chunk[Byte]
res6: fs2.Chunk[Byte] = empty
```

Adding a non-overloaded synonym for `to(Collector[A])` (as `toCollector` or something else) might be enough to fix this (I haven't tried it yet).

### PR DESCRIPTION
**Pull request by mpilquist**
`.to` was overloaded -- one took the `Collector` and the other took an implicit factory. When the target type was known, the 2.12 compiler was picking the factory overload. To fix, I removed the old overload -- or rather, made it `private[Stream]` so that it cannot be called but it stays around for binary compatibility reasons.

Note that in practice, any `s.compile.to[C]` can be written as `s.compile.to(C)` b/c `Collector` can be implicitly instantiated from any `Factory`. Only case where that's not true is when `C` doesn't implement `Factory` directly and instead, there's some implicit factory in scope.

### CODE REVIEW

File: core/shared/src/main/scala/fs2/Stream.scala [hunk 1]
```diff
@@ -2636,13 +2636,6 @@ final class Stream[+F[_], +O] private (private val free: FreeC[Nothing, O, Unit]
   )(f: (Stream[F, O], Stream[F2, O2]) => Stream[F2, O3]): Stream[F2, O3] =
     f(this, s2)
 
-  /**
-    * Applies the given sink to this stream.
-    */
-  @deprecated("Use .through instead", "1.0.2")
-  private[fs2] def to[F2[x] >: F[x]](f: Stream[F, O] => Stream[F2, Unit]): Stream[F2, Unit] =
```
Comment (mpilquist) [inline core/shared/src/main/scala/fs2/Stream.scala]: This is the reason for the mima exclusion. Not related to #1709 but noticed we can remove this safely now.
